# =============================================================================
# Application Infrastructure - Main Configuration
# =============================================================================
# This file defines the core infrastructure for your application
# Generated by scripts/setup-terraform-lambda.sh
# =============================================================================

terraform {
  required_version = ">= 1.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Backend configuration is loaded from environments/*.hcl files
  # Initialize with: terraform init -backend-config=environments/dev-backend.hcl
  backend "s3" {
    # Backend config provided via -backend-config flag
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = var.project_name
      Environment = var.environment
      ManagedBy   = "Terraform"
      Repository  = var.github_repo
    }
  }
}

# Get current AWS account ID
data "aws_caller_identity" "current" {}

# Get ECR repository (created by bootstrap)
data "aws_ecr_repository" "app" {
  name = var.ecr_repository_name
}
