# =============================================================================
# Terraform Backend Configuration for prod Environment
# =============================================================================
# Generated by scripts/setup-terraform-backend.sh
# Do not edit manually - regenerate from bootstrap outputs
# =============================================================================

bucket       = "aws-ai-terraform-state-234876310489"
key          = "environments/prod/terraform.tfstate"
region       = "us-east-1"
encrypt      = true
use_lockfile = true
