#!/bin/bash
# =============================================================================
# Generate Terraform Backend Configuration Files
# =============================================================================
# This script reads bootstrap outputs and generates backend config files
# for the application Terraform workspace
# =============================================================================

set -e

BOOTSTRAP_DIR="bootstrap"
TERRAFORM_DIR="terraform"
ENVIRONMENTS=("dev" "test" "prod")

echo "🔍 Reading bootstrap outputs..."

# Check if bootstrap directory exists
if [ ! -d "$BOOTSTRAP_DIR" ]; then
  echo "❌ Error: Bootstrap directory not found: $BOOTSTRAP_DIR"
  echo "   Please run bootstrap first: make bootstrap-apply"
  exit 1
fi

cd "$BOOTSTRAP_DIR"

# Check if Terraform is initialized
if [ ! -d ".terraform" ]; then
  echo "❌ Error: Bootstrap Terraform not initialized"
  echo "   Please run: make bootstrap-init"
  exit 1
fi

# Read bootstrap outputs
echo "📖 Fetching Terraform state bucket name..."
STATE_BUCKET=$(terraform output -raw terraform_state_bucket 2>/dev/null)
if [ -z "$STATE_BUCKET" ]; then
  echo "❌ Error: Could not read terraform_state_bucket output"
  echo "   Please ensure bootstrap is applied: make bootstrap-apply"
  exit 1
fi

AWS_REGION=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")

cd ..

echo "📝 Generating backend configuration files..."
echo "   State bucket: $STATE_BUCKET"
echo "   Region: $AWS_REGION"
echo ""

# Create environments directory if it doesn't exist
mkdir -p "$TERRAFORM_DIR/environments"

# Generate backend config for each environment
for ENV in "${ENVIRONMENTS[@]}"; do
  cat > "$TERRAFORM_DIR/environments/${ENV}-backend.hcl" <<EOF
# =============================================================================
# Terraform Backend Configuration for ${ENV} Environment
# =============================================================================
# Generated by scripts/setup-terraform-backend.sh
# Do not edit manually - regenerate from bootstrap outputs
# =============================================================================

bucket       = "${STATE_BUCKET}"
key          = "environments/${ENV}/terraform.tfstate"
region       = "${AWS_REGION}"
encrypt      = true
use_lockfile = true
EOF

  echo "✅ Created $TERRAFORM_DIR/environments/${ENV}-backend.hcl"
done

echo ""
echo "🎉 Backend configuration files created successfully!"
echo ""
echo "Next steps:"
echo "  1. Initialize Terraform for dev environment:"
echo "     make app-init-dev"
echo ""
echo "  2. Plan and apply application infrastructure:"
echo "     make app-plan-dev"
echo "     make app-apply-dev"
echo ""
